// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestHiberusNet.Models
{
    public partial class Estado
    {
        public Estado()
        {
            Terminales = new HashSet<Terminales>();
        }

        public int IdEstado { get; set; }
        public string EstadoName { get; set; }
        public string EstadoDesc { get; set; }

        public virtual ICollection<Terminales> Terminales { get; set; }
    }
}